CREATE TABLE agencies (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO agencies (name) VALUES ('Actuary, NYC Office of the (NYCOA)');
INSERT INTO agencies (name) VALUES ('Administrative Justice Coordinator, NYC Office of (AJC)');
INSERT INTO agencies (name) VALUES ('Administrative Trials and Hearings, Office of (OATH)');
INSERT INTO agencies (name) VALUES ('Aging, Department for the (DFTA)');
INSERT INTO agencies (name) VALUES ('Appointments, Mayor''s Office of (MOA)');
INSERT INTO agencies (name) VALUES ('Art Commission (see Design Commission)');
INSERT INTO agencies (name) VALUES ('Brooklyn Public Library (BPL)');
INSERT INTO agencies (name) VALUES ('Buildings, Department of (DOB)');
INSERT INTO agencies (name) VALUES ('Business Integrity Commission (BIC)');
INSERT INTO agencies (name) VALUES ('Campaign Finance Board (CFB)');
INSERT INTO agencies (name) VALUES ('Center for Economic Opportunity (CEO)');
INSERT INTO agencies (name) VALUES ('Center for Innovation through Data Intelligence (CIDI)');
INSERT INTO agencies (name) VALUES ('Chief Medical Examiner, NYC Office of (OCME)');
INSERT INTO agencies (name) VALUES ('Children''s Services, Administration for (ACS)');
INSERT INTO agencies (name) VALUES ('City Clerk, Office of the (CLERK)');
INSERT INTO agencies (name) VALUES ('City Council, New York (NYCC)');
INSERT INTO agencies (name) VALUES ('City Planning, Department of (DCP)');
INSERT INTO agencies (name) VALUES ('City University of New York (CUNY)');
INSERT INTO agencies (name) VALUES ('Citywide Administrative Services, Department of (DCAS)');
INSERT INTO agencies (name) VALUES ('Citywide Event Coordination and Management, Office of (CECM)');
INSERT INTO agencies (name) VALUES ('Civil Service Commission (CSC)');
INSERT INTO agencies (name) VALUES ('Civilian Complaint Review Board (CCRB)');
INSERT INTO agencies (name) VALUES ('Combat Domestic Violence, Mayor''s Office to (OCDV)');
INSERT INTO agencies (name) VALUES ('Commission on Gender Equity (CGE)');
INSERT INTO agencies (name) VALUES ('Commission to Combat Police Corruption (CCPC)');
INSERT INTO agencies (name) VALUES ('Community Affairs Unit (CAU)');
INSERT INTO agencies (name) VALUES ('Community Boards (CB)');
INSERT INTO agencies (name) VALUES ('Comptroller (COMP)');
INSERT INTO agencies (name) VALUES ('Conflicts of Interest Board (COIB)');
INSERT INTO agencies (name) VALUES ('Consumer Affairs, Department of (DCA)');
INSERT INTO agencies (name) VALUES ('Contract Services, Mayor''s Office of (MOCS)');
INSERT INTO agencies (name) VALUES ('Correction, Board of (BOC)');
INSERT INTO agencies (name) VALUES ('Correction, Department of (DOC)');
INSERT INTO agencies (name) VALUES ('Criminal Justice, Mayor''s Office of (MOCJ)');
INSERT INTO agencies (name) VALUES ('Cultural Affairs, Department of (DCLA)');
INSERT INTO agencies (name) VALUES ('Data Analytics, Mayor''s Office of (MODA)');
INSERT INTO agencies (name) VALUES ('Design and Construction, Department of (DDC)');
INSERT INTO agencies (name) VALUES ('Design Commission (DC)');
INSERT INTO agencies (name) VALUES ('District Attorney - Bronx County');
INSERT INTO agencies (name) VALUES ('District Attorney - Kings County (Brooklyn)');
INSERT INTO agencies (name) VALUES ('District Attorney - New York County (Manhattan)');
INSERT INTO agencies (name) VALUES ('District Attorney - Queens County');
INSERT INTO agencies (name) VALUES ('District Attorney - Richmond County (Staten Island)');
INSERT INTO agencies (name) VALUES ('Economic Development Corporation (EDC) or (NYCEDC)');
INSERT INTO agencies (name) VALUES ('Economic Opportunity, Mayor''s Office for');
INSERT INTO agencies (name) VALUES ('Education, Department of (DOE)');
INSERT INTO agencies (name) VALUES ('Elections, Board of (BOE)');
INSERT INTO agencies (name) VALUES ('Emergency Management, Office of (OEM)');
INSERT INTO agencies (name) VALUES ('Environmental Coordination, Mayor''s Office of (OEC)');
INSERT INTO agencies (name) VALUES ('Environmental Protection, Department of (DEP)');
INSERT INTO agencies (name) VALUES ('Equal Employment Practices Commission (EEPC)');
INSERT INTO agencies (name) VALUES ('Finance, Department of (DOF)');
INSERT INTO agencies (name) VALUES ('Fire Department, New York City (FDNY)');
INSERT INTO agencies (name) VALUES ('Fiscal Year 2005 Securitization Corporation');
INSERT INTO agencies (name) VALUES ('Food Policy Director, Office of the (See Long Term Planning)');
INSERT INTO agencies (name) VALUES ('GreeNYC (GNYC)');
INSERT INTO agencies (name) VALUES ('Health and Hospitals Corporation (HHC)');
INSERT INTO agencies (name) VALUES ('Health and Mental Hygiene, Department of (DOHMH)');
INSERT INTO agencies (name) VALUES ('Homeless Services, Department of (DHS)');
INSERT INTO agencies (name) VALUES ('Housing Authority, New York City (NYCHA)');
INSERT INTO agencies (name) VALUES ('Housing Preservation and Development, Department of (HPD)');
INSERT INTO agencies (name) VALUES ('Housing Recovery Operations (HRO)');
INSERT INTO agencies (name) VALUES ('Hudson Yards Infrastructure Corporation (HYIC)');
INSERT INTO agencies (name) VALUES ('Human Capital Development, Office of (See Workforce Development)');
INSERT INTO agencies (name) VALUES ('Human Resources Administration (HRA)');
INSERT INTO agencies (name) VALUES ('Human Rights, City Commission on (CCHR)');
INSERT INTO agencies (name) VALUES ('Immigrant Affairs, Mayor''s Office of (MOIA)');
INSERT INTO agencies (name) VALUES ('Independent Budget Office, NYC (IBO)');
INSERT INTO agencies (name) VALUES ('Information Technology and Telecommunications, Department of (DOITT)');
INSERT INTO agencies (name) VALUES ('Inspector General NYPD, Office of the (OIG-NYPD)');
INSERT INTO agencies (name) VALUES ('Intergovernmental Affairs, Mayor''s Office of (MOIGA)');
INSERT INTO agencies (name) VALUES ('Investigation, Department of (DOI)');
INSERT INTO agencies (name) VALUES ('Judiciary, Mayor''s Advisory Committee on the (ACJ)');
INSERT INTO agencies (name) VALUES ('Labor Relations, NYC Office of (OLR)');
INSERT INTO agencies (name) VALUES ('Landmarks Preservation Commission (LPC)');
INSERT INTO agencies (name) VALUES ('Law Department (LAW)');
INSERT INTO agencies (name) VALUES ('Library, Brooklyn Public (BPL)');
INSERT INTO agencies (name) VALUES ('Library, New York Public (NYPL)');
INSERT INTO agencies (name) VALUES ('Library, Queens Public (QL)');
INSERT INTO agencies (name) VALUES ('Loft Board (LOFT) (now see DOB)');
INSERT INTO agencies (name) VALUES ('Long-Term Planning & Sustainability, Office of (OLTPS)');
INSERT INTO agencies (name) VALUES ('Management and Budget, Office of (OMB)');
INSERT INTO agencies (name) VALUES ('Mayor''s Committee on City Marshals (MCCM)');
INSERT INTO agencies (name) VALUES ('Mayor''s Fund to Advance NYC (Mayor''s Fund)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office (OM)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office for International Affairs (IA)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office for People with Disabilities (MOPD)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office of Environmental Remediation (OER)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office of Special Projects & Community Events (MOSPCE)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office of Technology and Innovation (MOTI)');
INSERT INTO agencies (name) VALUES ('Mayor''s Office of Workforce Development');
INSERT INTO agencies (name) VALUES ('Media and Entertainment, Mayor''s Office of (MOME)');
INSERT INTO agencies (name) VALUES ('Media, NYC  (part of MOME)');
INSERT INTO agencies (name) VALUES ('New Business Acceleration Team (NBAT) (NYCBA)(part of SBS?)');
INSERT INTO agencies (name) VALUES ('New York City Transitional Finance Authority (TFA)');
INSERT INTO agencies (name) VALUES ('New York Public Library (NYPL)');
INSERT INTO agencies (name) VALUES ('NYC & Company (NYCGO)');
INSERT INTO agencies (name) VALUES ('NYC Employees'' Retirement System (NYCERS)');
INSERT INTO agencies (name) VALUES ('NYC Health + Hospitals (NYCHHC)');
INSERT INTO agencies (name) VALUES ('NYC Service (SERVICE)');
INSERT INTO agencies (name) VALUES ('NYC Young Men''s Initiative (YMI)');
INSERT INTO agencies (name) VALUES ('Operations, Mayor''s Office of (OPS)');
INSERT INTO agencies (name) VALUES ('Parks and Recreation, Department of (DPR) or (NYCDPR)');
INSERT INTO agencies (name) VALUES ('Payroll Administration, Office of (OPA)');
INSERT INTO agencies (name) VALUES ('People with Disabilities, Mayor''s Office of (MOPD)');
INSERT INTO agencies (name) VALUES ('Police Department (NYPD)');
INSERT INTO agencies (name) VALUES ('Police Pension Fund (PPF)');
INSERT INTO agencies (name) VALUES ('Probation, Department of (DOP)');
INSERT INTO agencies (name) VALUES ('Procurement Policy Board (PPB)');
INSERT INTO agencies (name) VALUES ('Public Administrator - Bronx County (BCPA)');
INSERT INTO agencies (name) VALUES ('Public Administrator - Kings County (KCPA)');
INSERT INTO agencies (name) VALUES ('Public Administrator - New York County (NYCountyPA)');
INSERT INTO agencies (name) VALUES ('Public Administrator - Queens County (QPA)');
INSERT INTO agencies (name) VALUES ('Public Administrator - Richmond County (RCPA)');
INSERT INTO agencies (name) VALUES ('Public Advocate (PUB ADV)');
INSERT INTO agencies (name) VALUES ('Quadrennial Advisory Commission');
INSERT INTO agencies (name) VALUES ('Queens Library (QL)');
INSERT INTO agencies (name) VALUES ('Records and Information Services, Department of (DORIS)');
INSERT INTO agencies (name) VALUES ('Rent Guidelines Board (RGB)');
INSERT INTO agencies (name) VALUES ('Sales Tax Asset Receivable Corporation (STAR)');
INSERT INTO agencies (name) VALUES ('Sanitation, Department of (DSNY)');
INSERT INTO agencies (name) VALUES ('School Construction Authority (SCA)');
INSERT INTO agencies (name) VALUES ('Small Business Services (SBS)');
INSERT INTO agencies (name) VALUES ('Special Enforcement, Mayor''s Office of (MOSE)');
INSERT INTO agencies (name) VALUES ('Special Narcotics Prosecutor, NYC Office of the (SNP)');
INSERT INTO agencies (name) VALUES ('Standards and Appeals, Board of (BSA)');
INSERT INTO agencies (name) VALUES ('Tax Appeals Tribunal, New York City (TAT) (See Tax Commission)');
INSERT INTO agencies (name) VALUES ('Tax Commission, New York City (TC)');
INSERT INTO agencies (name) VALUES ('Taxi and Limousine Commission (TLC)');
INSERT INTO agencies (name) VALUES ('Transportation, Department of (DOT) or (NYCDOT)');
INSERT INTO agencies (name) VALUES ('TSASC, Inc. (TSASC)');
INSERT INTO agencies (name) VALUES ('Veterans'' Services, Department of (DVS)');
INSERT INTO agencies (name) VALUES ('Water Board (NYWB)');
INSERT INTO agencies (name) VALUES ('Water Finance Authority, NYC Municipal (NYW)');
INSERT INTO agencies (name) VALUES ('Waterfront Management Advisory Board (WMAB)');
INSERT INTO agencies (name) VALUES ('Workforce Development, Mayor''s Office of (WKDEV)');
INSERT INTO agencies (name) VALUES ('Workforce Investment Board (WIB) (See Workforce Development)');
INSERT INTO agencies (name) VALUES ('Youth and Community Development, Department of (DYCD)');

CREATE TABLE subjects (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO subjects (name) VALUES ('Accounting');
INSERT INTO subjects (name) VALUES ('Advertising');
INSERT INTO subjects (name) VALUES ('Aged');
INSERT INTO subjects (name) VALUES ('Alcohol');
INSERT INTO subjects (name) VALUES ('Animal Welfare');
INSERT INTO subjects (name) VALUES ('Archaeology');
INSERT INTO subjects (name) VALUES ('Architecture');
INSERT INTO subjects (name) VALUES ('Art and Design');
INSERT INTO subjects (name) VALUES ('Athletics');
INSERT INTO subjects (name) VALUES ('Banks and Banking');
INSERT INTO subjects (name) VALUES ('Brooklyn');
INSERT INTO subjects (name) VALUES ('Bronx');
INSERT INTO subjects (name) VALUES ('Brooklyn (City)');
INSERT INTO subjects (name) VALUES ('Budget and Finance');
INSERT INTO subjects (name) VALUES ('Building Code');
INSERT INTO subjects (name) VALUES ('Building Construction');
INSERT INTO subjects (name) VALUES ('Buildings');
INSERT INTO subjects (name) VALUES ('Business');
INSERT INTO subjects (name) VALUES ('Celebrations and Parades');
INSERT INTO subjects (name) VALUES ('Cemeteries');
INSERT INTO subjects (name) VALUES ('Census');
INSERT INTO subjects (name) VALUES ('Charities');
INSERT INTO subjects (name) VALUES ('Children');
INSERT INTO subjects (name) VALUES ('City Planning');
INSERT INTO subjects (name) VALUES ('Civil Service');
INSERT INTO subjects (name) VALUES ('Climate');
INSERT INTO subjects (name) VALUES ('Coastal');
INSERT INTO subjects (name) VALUES ('Community Relations');
INSERT INTO subjects (name) VALUES ('Consumers');
INSERT INTO subjects (name) VALUES ('Conventions');
INSERT INTO subjects (name) VALUES ('Correction');
INSERT INTO subjects (name) VALUES ('Cost');
INSERT INTO subjects (name) VALUES ('Courts');
INSERT INTO subjects (name) VALUES ('Crime and Criminals');
INSERT INTO subjects (name) VALUES ('Criminal Justice');
INSERT INTO subjects (name) VALUES ('Culture');
INSERT INTO subjects (name) VALUES ('Data and Communications');
INSERT INTO subjects (name) VALUES ('Death');
INSERT INTO subjects (name) VALUES ('Demography and Population');
INSERT INTO subjects (name) VALUES ('Disability');
INSERT INTO subjects (name) VALUES ('Discrimination');
INSERT INTO subjects (name) VALUES ('Diseases');
INSERT INTO subjects (name) VALUES ('Drugs');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Education');
INSERT INTO subjects (name) VALUES ('Elections and Voting');
INSERT INTO subjects (name) VALUES ('Electric Power');
INSERT INTO subjects (name) VALUES ('Emergencies');
INSERT INTO subjects (name) VALUES ('Employment');
INSERT INTO subjects (name) VALUES ('Energy');
INSERT INTO subjects (name) VALUES ('Engineering');
INSERT INTO subjects (name) VALUES ('Environment');
INSERT INTO subjects (name) VALUES ('Equal Employment');
INSERT INTO subjects (name) VALUES ('Ethics');
INSERT INTO subjects (name) VALUES ('Ethnic groups');
INSERT INTO subjects (name) VALUES ('Families');
INSERT INTO subjects (name) VALUES ('Finance');
INSERT INTO subjects (name) VALUES ('Fire Fighting');
INSERT INTO subjects (name) VALUES ('Firearms');
INSERT INTO subjects (name) VALUES ('Food');
INSERT INTO subjects (name) VALUES ('Food supply');
INSERT INTO subjects (name) VALUES ('Fuels');
INSERT INTO subjects (name) VALUES ('Gambling');
INSERT INTO subjects (name) VALUES ('Geography');
INSERT INTO subjects (name) VALUES ('Government');
INSERT INTO subjects (name) VALUES ('Government - Citizen participation');
INSERT INTO subjects (name) VALUES ('Hazardous Materials');
INSERT INTO subjects (name) VALUES ('Health');
INSERT INTO subjects (name) VALUES ('History');
INSERT INTO subjects (name) VALUES ('Homeless Persons');
INSERT INTO subjects (name) VALUES ('Hospitals');
INSERT INTO subjects (name) VALUES ('Hotels');
INSERT INTO subjects (name) VALUES ('Housing');
INSERT INTO subjects (name) VALUES ('Housing - Limited Profit');
INSERT INTO subjects (name) VALUES ('Housing - Low Income');
INSERT INTO subjects (name) VALUES ('Human Rights');
INSERT INTO subjects (name) VALUES ('Immigration');
INSERT INTO subjects (name) VALUES ('Industries');
INSERT INTO subjects (name) VALUES ('Infrastructure');
INSERT INTO subjects (name) VALUES ('Insurance');
INSERT INTO subjects (name) VALUES ('Internet');
INSERT INTO subjects (name) VALUES ('Islands');
INSERT INTO subjects (name) VALUES ('Labor and Employment');
INSERT INTO subjects (name) VALUES ('Land Use');
INSERT INTO subjects (name) VALUES ('Landmarks');
INSERT INTO subjects (name) VALUES ('Languages');
INSERT INTO subjects (name) VALUES ('Laws and legislation');
INSERT INTO subjects (name) VALUES ('LGBTQ (Lesbian / Gay / Bisexual / Transgender / Queer or Questioning)');
INSERT INTO subjects (name) VALUES ('Libraries');
INSERT INTO subjects (name) VALUES ('Licenses and Permits');
INSERT INTO subjects (name) VALUES ('Manhattan');
INSERT INTO subjects (name) VALUES ('Maps');
INSERT INTO subjects (name) VALUES ('Markets');
INSERT INTO subjects (name) VALUES ('Mayor (Name)');
INSERT INTO subjects (name) VALUES ('Memorials');
INSERT INTO subjects (name) VALUES ('Mental Health');
INSERT INTO subjects (name) VALUES ('Monuments');
INSERT INTO subjects (name) VALUES ('Motor Vehicles');
INSERT INTO subjects (name) VALUES ('Museums');
INSERT INTO subjects (name) VALUES ('Neighborhoods');
INSERT INTO subjects (name) VALUES ('Nutrition');
INSERT INTO subjects (name) VALUES ('Officials and Employees');
INSERT INTO subjects (name) VALUES ('Parking');
INSERT INTO subjects (name) VALUES ('Parks and Recreation');
INSERT INTO subjects (name) VALUES ('Pensions');
INSERT INTO subjects (name) VALUES ('Pests');
INSERT INTO subjects (name) VALUES ('Police');
INSERT INTO subjects (name) VALUES ('Police - Community Relations');
INSERT INTO subjects (name) VALUES ('Police - Discipline');
INSERT INTO subjects (name) VALUES ('Politics and Government');
INSERT INTO subjects (name) VALUES ('Pollution');
INSERT INTO subjects (name) VALUES ('Poverty');
INSERT INTO subjects (name) VALUES ('Prices');
INSERT INTO subjects (name) VALUES ('Purchasing Methods');
INSERT INTO subjects (name) VALUES ('Public Authorities');
INSERT INTO subjects (name) VALUES ('Public Welfare');
INSERT INTO subjects (name) VALUES ('Queens');
INSERT INTO subjects (name) VALUES ('Real Property');
INSERT INTO subjects (name) VALUES ('Records');
INSERT INTO subjects (name) VALUES ('Recreation');
INSERT INTO subjects (name) VALUES ('Recycling');
INSERT INTO subjects (name) VALUES ('Refuse and Refuse Disposal');
INSERT INTO subjects (name) VALUES ('Religions');
INSERT INTO subjects (name) VALUES ('Rent Control');
INSERT INTO subjects (name) VALUES ('Rent Stabilization Law');
INSERT INTO subjects (name) VALUES ('Restaurants');
INSERT INTO subjects (name) VALUES ('Retail');
INSERT INTO subjects (name) VALUES ('Rivers');
INSERT INTO subjects (name) VALUES ('Sanitation');
INSERT INTO subjects (name) VALUES ('Schools');
INSERT INTO subjects (name) VALUES ('Schools - Administration');
INSERT INTO subjects (name) VALUES ('Schools - Charter');
INSERT INTO subjects (name) VALUES ('Schools - Parochial');
INSERT INTO subjects (name) VALUES ('Schools - Private');
INSERT INTO subjects (name) VALUES ('Schools - Buildings');
INSERT INTO subjects (name) VALUES ('Sewage');
INSERT INTO subjects (name) VALUES ('Small Business');
INSERT INTO subjects (name) VALUES ('Snow Removal');
INSERT INTO subjects (name) VALUES ('Special Districts');
INSERT INTO subjects (name) VALUES ('State of New York');
INSERT INTO subjects (name) VALUES ('Staten Island');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Statistics');
INSERT INTO subjects (name) VALUES ('Street Vendors');
INSERT INTO subjects (name) VALUES ('Streets - Maintenance and Repair');
INSERT INTO subjects (name) VALUES ('Streets and Highways');
INSERT INTO subjects (name) VALUES ('Students');
INSERT INTO subjects (name) VALUES ('Subways');
INSERT INTO subjects (name) VALUES ('Subways - Stations');
INSERT INTO subjects (name) VALUES ('Supplies');
INSERT INTO subjects (name) VALUES ('Surveying');
INSERT INTO subjects (name) VALUES ('Taxation');
INSERT INTO subjects (name) VALUES ('Taxation - Exemption from');
INSERT INTO subjects (name) VALUES ('Taxation - Real Property');
INSERT INTO subjects (name) VALUES ('Taxicabs');
INSERT INTO subjects (name) VALUES ('Teachers');
INSERT INTO subjects (name) VALUES ('Television');
INSERT INTO subjects (name) VALUES ('Terminals');
INSERT INTO subjects (name) VALUES ('Terrorism');
INSERT INTO subjects (name) VALUES ('Toilets');
INSERT INTO subjects (name) VALUES ('Tolls');
INSERT INTO subjects (name) VALUES ('Tourists');
INSERT INTO subjects (name) VALUES ('Traffic and Parking');
INSERT INTO subjects (name) VALUES ('Traffic Safety');
INSERT INTO subjects (name) VALUES ('Transit');
INSERT INTO subjects (name) VALUES ('Transit - Rapid');
INSERT INTO subjects (name) VALUES ('Transportation');
INSERT INTO subjects (name) VALUES ('Transportation - Finance');
INSERT INTO subjects (name) VALUES ('Transportation - School');
INSERT INTO subjects (name) VALUES ('Transportation- Planning');
INSERT INTO subjects (name) VALUES ('Trees');
INSERT INTO subjects (name) VALUES ('Trusts and Estates');
INSERT INTO subjects (name) VALUES ('Universities and Colleges');
INSERT INTO subjects (name) VALUES ('Vendors and Contracts');
INSERT INTO subjects (name) VALUES ('Veterans');
INSERT INTO subjects (name) VALUES ('Volunteers');
INSERT INTO subjects (name) VALUES ('Water');
INSERT INTO subjects (name) VALUES ('Water Supply');
INSERT INTO subjects (name) VALUES ('Weapons');
INSERT INTO subjects (name) VALUES ('Weather');
INSERT INTO subjects (name) VALUES ('Women');
INSERT INTO subjects (name) VALUES ('World Trade Center');
INSERT INTO subjects (name) VALUES ('Youth');


CREATE TABLE report_types (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO report_types (name) VALUES ('Adjudications / Decisions');
INSERT INTO report_types (name) VALUES ('Audit Report');
INSERT INTO report_types (name) VALUES ('Brochures');
INSERT INTO report_types (name) VALUES ('Budget / Finance');
INSERT INTO report_types (name) VALUES ('Bulletins');
INSERT INTO report_types (name) VALUES ('Calendars');
INSERT INTO report_types (name) VALUES ('Data / Statistics');
INSERT INTO report_types (name) VALUES ('Directives');
INSERT INTO report_types (name) VALUES ('Environmental Impact Statements - Draft');
INSERT INTO report_types (name) VALUES ('Environmental Impact Statements - Final');
INSERT INTO report_types (name) VALUES ('Executive Orders');
INSERT INTO report_types (name) VALUES ('Guides');
INSERT INTO report_types (name) VALUES ('Laws / Legislation');
INSERT INTO report_types (name) VALUES ('Manuals / Directories');
INSERT INTO report_types (name) VALUES ('Minutes');
INSERT INTO report_types (name) VALUES ('Newsletters / Other Serial Publications');
INSERT INTO report_types (name) VALUES ('Other');
INSERT INTO report_types (name) VALUES ('Plans');
INSERT INTO report_types (name) VALUES ('Press Releases');
INSERT INTO report_types (name) VALUES ('Proceedings');
INSERT INTO report_types (name) VALUES ('Reports - Annual');
INSERT INTO report_types (name) VALUES ('Reports - Biennial');
INSERT INTO report_types (name) VALUES ('Reports - Monthly');
INSERT INTO report_types (name) VALUES ('Reports - Weekly');
INSERT INTO report_types (name) VALUES ('Reports - Other (Consultant/Staff)');
INSERT INTO report_types (name) VALUES ('Studies');

CREATE TABLE languages (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO languages (name) VALUES ('English');
INSERT INTO languages (name) VALUES ('Spanish');
INSERT INTO languages (name) VALUES ('Chinese');
INSERT INTO languages (name) VALUES ('Russian');
INSERT INTO languages (name) VALUES ('Arabic');
INSERT INTO languages (name) VALUES ('Bengali');
INSERT INTO languages (name) VALUES ('French');
INSERT INTO languages (name) VALUES ('Haitian Creole');
INSERT INTO languages (name) VALUES ('Italian');
INSERT INTO languages (name) VALUES ('Korean');
INSERT INTO languages (name) VALUES ('Polish');
INSERT INTO languages (name) VALUES ('Urdu');
INSERT INTO languages (name) VALUES ('Yiddish');

CREATE TABLE neighborhoods (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO neighborhoods (name) VALUES ('Bronx - Barretto Point');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Bathgate');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Baychester');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Bedford Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Belmont');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Bronx Park/River');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Castle Hill');
INSERT INTO neighborhoods (name) VALUES ('Bronx - City Island');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Claremont');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Clason Point');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Concourse');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Co-op City');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Country Club');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Crotona Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Eastchester Village');
INSERT INTO neighborhoods (name) VALUES ('Bronx - East Tremont');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Edenwald');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Edgewater Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Ferry Point');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Fieldston');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Fordham');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Fordham Heights');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Gun Hill');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Harding Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Highbridge');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Hunt''s Point');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Jerome Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Kingsbridge');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Kingsbridge Heights');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Lavonia');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Locust Point');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Longwood/Foxhurst');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Lower Harlem River');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Macomb''s Dam');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Marble Hill');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Melrose');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Morrisania');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Morris Heights');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Morris Park');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Mott Haven');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Mount Eden');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Mount St. Vincent');
INSERT INTO neighborhoods (name) VALUES ('Bronx - North New York');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Norwood');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Olinville');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Parkchester');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Park Stratton/ Versailles');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Pelham Garden');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Pelham Pkwy Area');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Port Morris');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Riverdale');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Rodman''s Neck');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Rosedale');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Schuylerville');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Silver Beach');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Soundview and Sound View/Bruckner');
INSERT INTO neighborhoods (name) VALUES ('Bronx - South Bronx');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Spuyten Duyvil');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Throgs Neck');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Tremont');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Unionport');
INSERT INTO neighborhoods (name) VALUES ('Bronx - University Heights');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Van Cordlandt Village');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Van Nest');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Wakefield');
INSERT INTO neighborhoods (name) VALUES ('Bronx - West Farms');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Westchester');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Westchester Heights');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Westchester Village');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Williamsbridge');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Woodlawn');
INSERT INTO neighborhoods (name) VALUES ('Bronx - Woodstock');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bath Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bay Ridge');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bedford-Stuyvesant');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bensonhurst');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bergen Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Between the Bridges');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Boerum Hill');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Borough Park');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Brighton Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Brooklyn Civic Center');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Brooklyn Heights');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Brownsville');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bush Terminal');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Bushwick');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Cadman Plaza');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Canarsie');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Carroll Gardens');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Central Brooklyn Waterfront');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Central Business District');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Civic Center');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Clinton Hill');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Cobble Hill-Carroll Gardens');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Coney Island');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Crown Heights');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Downtown Brooklyn');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - DUMBO');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Dyker Heights');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - East Flatbush');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - East New York');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - English Kills');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Flatbush');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Flatlands');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Floyd Bennett Fields');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Fort Greene');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Fort Hamilton');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Fulton Ferry');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Georgetown');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Gerritsen Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Gowanus');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Gravesend');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Greenpoint');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Highland Park');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Kensington');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Kings Highway');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Madison');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Manhattan Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Marine Park');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Midwood');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Mill Basin');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Mill Island');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - New Lots');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Newtown Creek');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - New Utrecht');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Northside');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Oriental Beach Area');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Paerdegat Basin');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Park Slope');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Plum Beach');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Prospect Heights');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Red Hook');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Sea Gate');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Sheepshead Bay');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - South Brooklyn-Boerum Hill');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Spring Creek');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Starrett City');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Stuyvesant Heights');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Sunset Park');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Waterfront, Central Brooklyn');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Williamsburg');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Willow Town');
INSERT INTO neighborhoods (name) VALUES ('Brooklyn - Windsor Terrace');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Battery');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Battery Park City');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Beekman Place');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Bloomingdale');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Bowling Green');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Brooklyn Bridge South');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Carnegie Hall Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Carnegie Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Cathedral Parkway Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Central Business District');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Central Harlem');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Central Park South (Grand Army Plaza)/Carnegie Hall/Columbus Circle');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Central Park West Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Chatham Green Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Chelsea');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Cherry Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Chinatown');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Civic Center');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Clinton');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Columbus Circle');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Cooper Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Corlear''s Hook');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Dyckman Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - East Harlem');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - East River proposed projects/Riverwalk');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - East Side');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - East Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Edgecomb Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Fifty-Second Street');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Financial-Wall Street Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Fort George');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Forty-Second Street');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Garment District');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Gashouse District');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Gracie Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Gramercy Park Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Grand Central Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Greeley Square - Herald Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Greenwich Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Ground Zero');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Hamilton Grange Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Hamilton Heights');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Harlem');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Harlem/125th Street');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Hell''s Kitchen');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Herald Square Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Horn''s Hook');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Inwood');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Jefferson Park');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Kip''s Bay');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Knickerbocker Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Lenox Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Lincoln Square - West Side (59th-79th Streets)');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Little Italy');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Lower East Side');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Lower Manhattan');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Madison Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Manhattan Bridge South');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Manhattan - Hudson Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Manhattan Landing');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Manhattanville');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Midtown');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Morningside');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Mount Morris Park Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Murray Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - NoHo');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - NoLita');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - North River');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Peter Cooper Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Ruppert Houses Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - St. Mark''s Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Seward Park');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Sherman''s Creek');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Sixth Avenue');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - SoHo');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - South Street Seaport - Fulton Market');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - South Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Striver''s Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Stuyvesant Town - Peter Cooper Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Sugar Hill');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Sutton Place Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - The "Swamp"');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Tompkins Square - East Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Tribeca');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Tubby Hook');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Tudor City');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Turtle Bay');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Two Bridges - Corlear''s Hook');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Union Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - United Nations - Turtle Bay - Tudor City');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Washington Heights');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Washington Market Area');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Washington Square');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West 85th Street');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Midtown');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Side - General');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Side (79th - 96th Streets)');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Side (96th - 110th Streets)');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Side - Lincoln Square (59th - 79th Streets)');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - West Village');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - World Trade Center Area (Ground Zero)');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Yorkville');
INSERT INTO neighborhoods (name) VALUES ('Manhattan - Yorkville - Ruppert');
INSERT INTO neighborhoods (name) VALUES ('Queens - Addisleigh Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Arverne');
INSERT INTO neighborhoods (name) VALUES ('Queens - Auburndale');
INSERT INTO neighborhoods (name) VALUES ('Queens - Baisley');
INSERT INTO neighborhoods (name) VALUES ('Queens - Bayside');
INSERT INTO neighborhoods (name) VALUES ('Queens - Belle Harbor');
INSERT INTO neighborhoods (name) VALUES ('Queens - Bellerose');
INSERT INTO neighborhoods (name) VALUES ('Queens - Breezy Point');
INSERT INTO neighborhoods (name) VALUES ('Queens - Briarwood');
INSERT INTO neighborhoods (name) VALUES ('Queens - Broad Channel');
INSERT INTO neighborhoods (name) VALUES ('Queens - Cambria Heights');
INSERT INTO neighborhoods (name) VALUES ('Queens - College Point');
INSERT INTO neighborhoods (name) VALUES ('Queens - Corona');
INSERT INTO neighborhoods (name) VALUES ('Queens - Cypress Hills');
INSERT INTO neighborhoods (name) VALUES ('Queens - Douglaston');
INSERT INTO neighborhoods (name) VALUES ('Queens - East Elmhurst');
INSERT INTO neighborhoods (name) VALUES ('Queens - Edgemere');
INSERT INTO neighborhoods (name) VALUES ('Queens - Far Rockaway');
INSERT INTO neighborhoods (name) VALUES ('Queens - Floral Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Flushing');
INSERT INTO neighborhoods (name) VALUES ('Queens - Forest Hills');
INSERT INTO neighborhoods (name) VALUES ('Queens - Fresh Meadows');
INSERT INTO neighborhoods (name) VALUES ('Queens - Glendale');
INSERT INTO neighborhoods (name) VALUES ('Queens - Hammels');
INSERT INTO neighborhoods (name) VALUES ('Queens - Hillside');
INSERT INTO neighborhoods (name) VALUES ('Queens - Hollis');
INSERT INTO neighborhoods (name) VALUES ('Queens - Hollis Hills');
INSERT INTO neighborhoods (name) VALUES ('Queens - Howard Beach');
INSERT INTO neighborhoods (name) VALUES ('Queens - Hunter''s Point');
INSERT INTO neighborhoods (name) VALUES ('Queens - Jackson Heights');
INSERT INTO neighborhoods (name) VALUES ('Queens - Jamaica');
INSERT INTO neighborhoods (name) VALUES ('Queens - Kew Gardens');
INSERT INTO neighborhoods (name) VALUES ('Queens - Kew Gardens Hills');
INSERT INTO neighborhoods (name) VALUES ('Queens - Kissena Park Area');
INSERT INTO neighborhoods (name) VALUES ('Queens - Laurelton');
INSERT INTO neighborhoods (name) VALUES ('Queens - LeFrak City');
INSERT INTO neighborhoods (name) VALUES ('Queens - Lindenwood');
INSERT INTO neighborhoods (name) VALUES ('Queens - Little Neck');
INSERT INTO neighborhoods (name) VALUES ('Queens - Locust Manor');
INSERT INTO neighborhoods (name) VALUES ('Queens - Long Island City');
INSERT INTO neighborhoods (name) VALUES ('Queens - Malba');
INSERT INTO neighborhoods (name) VALUES ('Queens - Maspeth');
INSERT INTO neighborhoods (name) VALUES ('Queens - Middle Village');
INSERT INTO neighborhoods (name) VALUES ('Queens - Morris Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Murray Hill');
INSERT INTO neighborhoods (name) VALUES ('Queens - Nassau Heights');
INSERT INTO neighborhoods (name) VALUES ('Queens - Neponsit');
INSERT INTO neighborhoods (name) VALUES ('Queens - Oakland Gardens');
INSERT INTO neighborhoods (name) VALUES ('Queens - Ozone Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Queens Village');
INSERT INTO neighborhoods (name) VALUES ('Queens - Rego Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Richmond Hill');
INSERT INTO neighborhoods (name) VALUES ('Queens - Ridgewood');
INSERT INTO neighborhoods (name) VALUES ('Queens - Rochdale Village');
INSERT INTO neighborhoods (name) VALUES ('Queens - Rockaway');
INSERT INTO neighborhoods (name) VALUES ('Queens - Rockaway Park');
INSERT INTO neighborhoods (name) VALUES ('Queens - Rosedale');
INSERT INTO neighborhoods (name) VALUES ('Queens - Roxbury');
INSERT INTO neighborhoods (name) VALUES ('Queens - St. Albans');
INSERT INTO neighborhoods (name) VALUES ('Queens - South Flushing');
INSERT INTO neighborhoods (name) VALUES ('Queens - South Jamaica');
INSERT INTO neighborhoods (name) VALUES ('Queens - Springfield Gardens');
INSERT INTO neighborhoods (name) VALUES ('Queens - Steinway');
INSERT INTO neighborhoods (name) VALUES ('Queens - Sunnyside');
INSERT INTO neighborhoods (name) VALUES ('Queens - Winfield');
INSERT INTO neighborhoods (name) VALUES ('Queens - Woodhaven');
INSERT INTO neighborhoods (name) VALUES ('Queens - Woodside');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Annadale');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Arden Heights');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Arlington');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Arrochar');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Bay Terrace');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Bodine Creek Area');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Bloomfield');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Bluebelt');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Bull''s Head');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Castleton Corners');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Charleston');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Chelsea');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Clifton');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Clove Lakes Area');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Concord');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Dongan Hills');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Egbertville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Elm Park');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Eltingville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Emerson Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Fairview');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Fort Wadsworth Area');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Fox Hills');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Fresh Kills');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Graniteville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Grasmere');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Great Kills');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Greenbelt');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Greenridge');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Grymes Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Hamilton Park');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Heartlands Village');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Homeport');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Howland Hook');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Huguenot');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Island of Meadow');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - La Tourette Park Area');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Lighthouse Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Linoleumville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Livingston');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Long Neck');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Manor Heights');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Mariners''s Harbor');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Meier''s Corner');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Midland Beach');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Miller Field');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Mount Loretto');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Naval Base');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - New Brighton');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - New Springville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Oakwood');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Ocean Breeze');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Old Place');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Old Town');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Park Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Pleasant Plains');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Port Ivory');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Port Richmond');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Prall''s Island');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Prince''s Bay');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Randall Manor');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Richmond');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Richmondtown');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Ricmond Valley');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Rosebank');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Rossville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - St. George');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Sandy Ground');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Seaview');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Shore Acres');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Silver Lake');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Snug Harbor');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - South Beach');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - South Richmond');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Stapleton');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Summerfield');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Sunnyside');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Teleport');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Todd Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Tompkinsville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Tottenville');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Travis');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Ward Hill');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - West Brighton');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Westerleigh');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Wetlands');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Willowbrook');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Woodland Beach');
INSERT INTO neighborhoods (name) VALUES ('Staten Island - Woodrow');

CREATE TABLE boroughs (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO boroughs (name) VALUES ('Bronx');
INSERT INTO boroughs (name) VALUES ('Brooklyn');
INSERT INTO boroughs (name) VALUES ('Manhattan');
INSERT INTO boroughs (name) VALUES ('Queens');
INSERT INTO boroughs (name) VALUES ('Staten Island');

CREATE TABLE school_districts (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO school_districts (name) VALUES ('District 1');
INSERT INTO school_districts (name) VALUES ('District 2');
INSERT INTO school_districts (name) VALUES ('District 3');
INSERT INTO school_districts (name) VALUES ('District 4');
INSERT INTO school_districts (name) VALUES ('District 5');
INSERT INTO school_districts (name) VALUES ('District 6');
INSERT INTO school_districts (name) VALUES ('District 7');
INSERT INTO school_districts (name) VALUES ('District 8');
INSERT INTO school_districts (name) VALUES ('District 9');
INSERT INTO school_districts (name) VALUES ('District 10');
INSERT INTO school_districts (name) VALUES ('District 11');
INSERT INTO school_districts (name) VALUES ('District 12');
INSERT INTO school_districts (name) VALUES ('District 13');
INSERT INTO school_districts (name) VALUES ('District 14');
INSERT INTO school_districts (name) VALUES ('District 15');
INSERT INTO school_districts (name) VALUES ('District 16');
INSERT INTO school_districts (name) VALUES ('District 17');
INSERT INTO school_districts (name) VALUES ('District 18');
INSERT INTO school_districts (name) VALUES ('District 19');
INSERT INTO school_districts (name) VALUES ('District 20');
INSERT INTO school_districts (name) VALUES ('District 21');
INSERT INTO school_districts (name) VALUES ('District 22');
INSERT INTO school_districts (name) VALUES ('District 23');
INSERT INTO school_districts (name) VALUES ('District 24');
INSERT INTO school_districts (name) VALUES ('District 25');
INSERT INTO school_districts (name) VALUES ('District 26');
INSERT INTO school_districts (name) VALUES ('District 27');
INSERT INTO school_districts (name) VALUES ('District 28');
INSERT INTO school_districts (name) VALUES ('District 29');
INSERT INTO school_districts (name) VALUES ('District 30');
INSERT INTO school_districts (name) VALUES ('District 31');
INSERT INTO school_districts (name) VALUES ('District 32');
INSERT INTO school_districts (name) VALUES ('District 75');
INSERT INTO school_districts (name) VALUES ('District 79');

CREATE TABLE community_board_districts (
  id              SERIAL PRIMARY KEY,
  name            VARCHAR(128) NOT NULL
);

INSERT INTO school_districts (name) VALUES ('Bronx 1');
INSERT INTO school_districts (name) VALUES ('Bronx 2');
INSERT INTO school_districts (name) VALUES ('Bronx 3');
INSERT INTO school_districts (name) VALUES ('Bronx 4');
INSERT INTO school_districts (name) VALUES ('Bronx 5');
INSERT INTO school_districts (name) VALUES ('Bronx 6');
INSERT INTO school_districts (name) VALUES ('Bronx 7');
INSERT INTO school_districts (name) VALUES ('Bronx 8');
INSERT INTO school_districts (name) VALUES ('Bronx 9');
INSERT INTO school_districts (name) VALUES ('Bronx 10');
INSERT INTO school_districts (name) VALUES ('Bronx 11');
INSERT INTO school_districts (name) VALUES ('Bronx 12');
INSERT INTO school_districts (name) VALUES ('Brooklyn 1');
INSERT INTO school_districts (name) VALUES ('Brooklyn 2');
INSERT INTO school_districts (name) VALUES ('Brooklyn 3');
INSERT INTO school_districts (name) VALUES ('Brooklyn 4');
INSERT INTO school_districts (name) VALUES ('Brooklyn 5');
INSERT INTO school_districts (name) VALUES ('Brooklyn 6');
INSERT INTO school_districts (name) VALUES ('Brooklyn 7');
INSERT INTO school_districts (name) VALUES ('Brooklyn 8');
INSERT INTO school_districts (name) VALUES ('Brooklyn 9');
INSERT INTO school_districts (name) VALUES ('Brooklyn 10');
INSERT INTO school_districts (name) VALUES ('Brooklyn 11');
INSERT INTO school_districts (name) VALUES ('Brooklyn 12');
INSERT INTO school_districts (name) VALUES ('Brooklyn 13');
INSERT INTO school_districts (name) VALUES ('Brooklyn 14');
INSERT INTO school_districts (name) VALUES ('Brooklyn 15');
INSERT INTO school_districts (name) VALUES ('Brooklyn 16');
INSERT INTO school_districts (name) VALUES ('Brooklyn 17');
INSERT INTO school_districts (name) VALUES ('Brooklyn 18');
INSERT INTO school_districts (name) VALUES ('Manhattan 1');
INSERT INTO school_districts (name) VALUES ('Manhattan 2');
INSERT INTO school_districts (name) VALUES ('Manhattan 3');
INSERT INTO school_districts (name) VALUES ('Manhattan 4');
INSERT INTO school_districts (name) VALUES ('Manhattan 5');
INSERT INTO school_districts (name) VALUES ('Manhattan 6');
INSERT INTO school_districts (name) VALUES ('Manhattan 7');
INSERT INTO school_districts (name) VALUES ('Manhattan 8');
INSERT INTO school_districts (name) VALUES ('Manhattan 9');
INSERT INTO school_districts (name) VALUES ('Manhattan 10');
INSERT INTO school_districts (name) VALUES ('Manhattan 11');
INSERT INTO school_districts (name) VALUES ('Manhattan 12');
INSERT INTO school_districts (name) VALUES ('Queens 1');
INSERT INTO school_districts (name) VALUES ('Queens 2');
INSERT INTO school_districts (name) VALUES ('Queens 3');
INSERT INTO school_districts (name) VALUES ('Queens 4');
INSERT INTO school_districts (name) VALUES ('Queens 5');
INSERT INTO school_districts (name) VALUES ('Queens 6');
INSERT INTO school_districts (name) VALUES ('Queens 7');
INSERT INTO school_districts (name) VALUES ('Queens 8');
INSERT INTO school_districts (name) VALUES ('Queens 9');
INSERT INTO school_districts (name) VALUES ('Queens 10');
INSERT INTO school_districts (name) VALUES ('Queens 11');
INSERT INTO school_districts (name) VALUES ('Queens 12');
INSERT INTO school_districts (name) VALUES ('Queens 13');
INSERT INTO school_districts (name) VALUES ('Queens 14');
INSERT INTO school_districts (name) VALUES ('Staten Island 1');
INSERT INTO school_districts (name) VALUES ('Staten Island 2');
INSERT INTO school_districts (name) VALUES ('Staten Island 3');